---
- hosts: prod
  become: yes 
  tasks:
  - name: deploying war file to prod server
    copy:
      src: /home/alicewangngc/git/hello-world-war/target/hello-world-war-1.0.0.war
      dest: /usr/share/tomcat/webapps/hello.war

